use_frameworks!

platform :ios, '9.0'

target 'MYPickerView_Example' do
  pod 'Masonry'
  pod 'MYPickerView', :path => '../'

  target 'MYPickerView_Tests' do
    inherit! :search_paths

    
  end
end
